### PR TITLE
Update User Guide for v1.1

### LINKED ISSUE #8: Update README page to match project details
Add a UI mockup of intended final product. 

Update all contents to match project.

Update the link of the GitHub Actions build status badge (Build Status) so that it reflects the build status of team repo.

Acknowledge the original source of the code.

### PR DESCRIPTION
**Pull request by vevek**
- Some screenshots need to be edited in future versions. Currently left as placeholders.
- Some features listed as they would be added in future versions.

### CODE REVIEW

**Comment by samuelfangjw** [comment]
seems like the ci is failing due to checkstyle issues
```
ERROR:../docs/UserGuide.md:213: no newline at EOF.
WARN:../README.md:15: trailing whitespace.
```

**Comment by samuelfangjw** [comment]
Just realised you accidentally changed the user guide instead of the readme haha! Might want to edit the title :)

**Comment by vevek** [comment]
@samuelfangjw thanks. I have updated the title and the description.

**Comment by vevek** [comment]
Pull Request was closed due to deletion of branch. No merging was done.

**Pull request closed without merging**
