### PR TITLE
Update Deadline, Todo and relevant models as separate entities

### LINKED ISSUE #87: Update Deadlines & Todos as separate entities

### PR DESCRIPTION
**Pull request by vevek**
Closes #87

### CODE REVIEW

**Comment by vevek** [comment]
All the models, storage and tests have been updated. PR is ready for review. Thanks!

**Comment by vevek** [comment]
Tests aren't sufficient, but we'll ignore that for now so that the rest can proceed. I'll add more tests over time.

**Review by samuelfangjw — DISMISSED** [review]
LGTM

**Review by samuelfangjw — APPROVED** [review]
Should be good once CI passes. LGTM.

**Pull request merged**
