### PR TITLE
Bunch of bug fixes

### LINKED ISSUE #260: Standardise capital letters in feedback messages shown to users

### LINKED ISSUE #288: [PE-D] [UG] Specify primary key constraints for the models: todos, deadline, groupmates, contacts...
This is a suggestion to include the primary key constraints for the models. Currently, all models except for deadline and event are constrained by only the "name"/"description" fields. However, deadline and events are allowed to share the same name as long as there exists at least one other field that is different. If this behavior is as intended, I would suggest including it under the User Guide.

Thanks for reviewing.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: aaronsms/ped#5

### LINKED ISSUE #293: Update D command help message
Screenshot 2021-04-04 at 12 13 37 AM

UpdateD doesn't show /by in example

### LINKED ISSUE #296: [PE-D] addP: Inconsistency between UG and error feedback message
## How to reproduce
1. Launch CoLAB
1. Execute `addP n/---`
1. Observe the error feedback message
1. Open the UG
1. Navigate to the `addP` section.
1. Under the Parameters subsection, click on the link to the format specification (`NAME`)
1. Observe the restriction on the name.

## Expected result
The restrictions listed are the same

## Actual result
In the UG, it does not specify that spaces are allowed in project name, as shown:

In CoLAB, the error feedback message specifies that spaces are allowed in project name, as shown:

## Justification for severity
Very low severity was given because the user can probably figure this out on their own (such as via the example data), and the in-app version (more likely to be accessed to the user) is correct. So, not much inconvenience is likely. That said, it is still an inconsistency.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: benedictkhoomw/ped#3

### LINKED ISSUE #313: [PE-D] Allowing project name updates for the same name as original project name
When updating the project name to a new name, the program allows even if the new name is the same as the old one.

Maybe it is better to notify users that the new name is the same as the original one!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#1

### LINKED ISSUE #314: [PE-D] Allowing todo updating for the same todo name
Similar to the previous issue, when updating the todo name to a new name, the program allows even if the new name is the same as the old one.

Maybe it will be better to let the user know that the new name is the same as the old one!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#2

### LINKED ISSUE #315: [PE-D] Mark a todo done when it is already done
Maybe it will be better to let users know that the todo is already done, instead of allowing users to mark it done multiple times!!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#3

### LINKED ISSUE #317: [PE-D] Allowing deadline updates for the same name and deadline
It might be better to let users know their input for the new update is the same as the original one!!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#5

### LINKED ISSUE #318: [PE-D] Error message mismatch for Time
When user key in a time with correct format but invalid number (out of range), it might be confusing for user when the displayed error message is wrong format.
It can be extremely confusing when the time keyed in is 2400, as some may mistake 2400 as 0000.
It might be good to notify users the maximum hour allowed is 23!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#6

### LINKED ISSUE #319: [PE-D] Updates related to event is allowing same updates as the original
Similar to previous issues, it might be better to notify users that their updates about the name, date, time and weekly repeat status are the same as the original!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#7

### LINKED ISSUE #323: [PE-D] Allowing contacts related updated to be the same as original
Similar to previous issues, if the updates are the same as original info, it might be better to let the users know!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#11

### LINKED ISSUE #325: [PE-D] Singular and plural grammar
Maybe it will be better to change to contact/contacts so that it is appropriate when only 1 contact is listed!

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Icelenaugust/ped#13

### LINKED ISSUE #351: Check for unchanged parameters when updating Contact, Project, Todo, Deadline, Event & Groupmate

### LINKED ISSUE #352: Prevent marking of a Deadline as done when it is already done

### PR DESCRIPTION
**Pull request by vevek**
Closes #296
Closes #288
Closes #325
Closes #314
Closes #351
Closes #293
Closes #313
Closes #315
Closes #352
Closes #317
Closes #319
Closes #323
Closes #318
Closes #260

The following message capitalisations were left untouched. LMK if you want them in lower caps too.
Screenshot 2021-04-11 at 03 50 35

AND

Screenshot 2021-04-11 at 03 54 35

### CODE REVIEW

**Comment by vevek** [comment]
Ready for review!

**Comment by vevek** [comment]
Ready for review!

**Comment by vevek** [comment]
Updated the message to -> This would cover all cases of 0 or more contacts.
Screenshot 2021-04-11 at 16 12 04

Screenshot 2021-04-11 at 16 12 30

**Comment by vevek** [comment]
Btw @samuelfangjw what do you think of these?

The following message capitalisations were left untouched. LMK if you want them in lower caps too. 
Screenshot 2021-04-11 at 03 50 35

AND

Screenshot 2021-04-11 at 03 54 35

**Review by samuelfangjw — APPROVED** [review]
LGTM!

**Pull request merged**
