### PR TITLE
Update user guide on details of view command

### PR DESCRIPTION
**Pull request by samuelfangjw**
#6 
Also change references of AB3 to CoLAB.

### CODE REVIEW

**Comment by vevek** [comment]
@samuelfangjw Looks great! Please add the changes you have added to features to the table of contents.

**Comment by samuelfangjw** [comment]
> @samuelfangjw Looks great! Please add the changes you have added to features to the table of contents.

Done! Forgot to update the table of contents when resolving the merge conflict. How does the latest commit look?

**Comment by vevek** [comment]
Nice work! LGTM!

**Review by vevek — COMMENTED** [review]
LGTM

**Pull request merged**
